import "./globals.css";
import { Inter } from "next/font/google";
import { AppContextProvider } from "../Context/AppContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Leandro Aguilar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={inter.className}>{children}</body>
      </AppContextProvider>
    </html>
  );
}
