import "./globals.css";

import { AppContextProvider } from "../context/AppContext";
import { font } from "./font";

export const metadata = {
  title: "Leandro Aguilar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={font.className}>{children}</body>
      </AppContextProvider>
    </html>
  );
}
